# Generated by Django 4.1.3 on 2022-12-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
