# Generated by Django 4.1.3 on 2022-12-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
